# -*- coding: utf-8 -*-
"""DDOSATTACK.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qt2zzTB7mCSr2t4psF-iSj2Wnoeo_mAg
"""

import math
import collections

# Constants
THRESHOLD = 7.5  # Entropy threshold to detect DDoS attack

def calculate_entropy(data):
    # Calculate the frequency of each byte value in the data
    byte_count = collections.Counter(data)

    # Calculate the entropy using Shannon's formula
    entropy = 0
    total_bytes = len(data)

    for count in byte_count.values():
        probability = count / total_bytes
        entropy += probability * math.log2(probability)

    return -entropy

def detect_ddos_attack(data):
    entropy = calculate_entropy(data)
    if entropy > THRESHOLD:
        print("DDoS attack detected! Entropy:", entropy)
    else:
        print("No DDoS attack detected. Entropy:", entropy)

# Example usage
network_traffic = b'\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f'
detect_ddos_attack(network_traffic)